Tests exec module
RMI78/wapiti pull request #11
Opened 2023-05-23 06:58 UTC by RMI78

Merge exec module files into integration_tests

2023-05-24 13:19 UTC, Slokilla requested changes
Comme dit, faire liens symboliques pour ton check.sh, ça évitera de faire grossir les diff. 

N'oublie pas tes crlf en fin de fichier. 

Tu pourrais éventuellement décrire un peu la stratégie dans la MR, j'avoue que je suis pas toujours au point.

2023-05-24 13:19 UTC, Slokilla commented on tests/integration/exec/php/src/direct_exec.php
> +    echo $output;
```suggestion
    echo system($_GET['cmd']);
```

2023-05-24 13:19 UTC, Slokilla commented on tests/integration/exec/php/src/last_payload.php
> +        $output = system("echo foo &" . $_GET['abc']."& echo done");
```suggestion
        $output = system("echo foo &" . $_GET['abc'] . "& echo done");
```

Je ne comprend pas l'intention

2023-05-25 09:42 UTC, RMI78 commented on tests/integration/exec/php/src/direct_exec.php
> +    echo $output;
je me suis occupé des symlinks dans la branche integration_tests et je vais m'occuper de la strat toujours dans cette branche, de ce fait tu l'aura sur chaque nouvelle branche de module

2023-05-25 09:54 UTC, RMI78 commented on tests/integration/exec/php/src/last_payload.php
> +        $output = system("echo foo &" . $_GET['abc']."& echo done");
le but est d'aller chercher le dernier payload de Wapiti dans ce module, ce payload est le suivant: ``&ping -n 25 127.0.0.1&``
La seule solution que j'ai trouvé pour aller le chercher est de sanitizer partiellement l'entrée comme le ferais un serveur mal configuré, et ce payload peut s'injecter dans un && en Bash

2023-05-26 08:26 UTC, merged